// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonTitle: typeof import('./src/components/CommonTitle.vue')['default']
    Heart: typeof import('./src/components/Heart.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    Button: typeof import('./src/components/Button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialPlatform: typeof import('./src/components/SocialPlatform.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export {}
