// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BattlefieldReport: typeof import('./src/components/BattlefieldReport.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CommonTitle: typeof import('./src/components/CommonTitle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Heart: typeof import('./src/components/Heart.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    ResourcesCollection: typeof import('./src/components/ResourcesCollection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialPlatform: typeof import('./src/components/SocialPlatform.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}

export {}
